# Version updates paused at the repository owner's request.
version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 0
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: pip
    open-pull-requests-limit: 0
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: cargo
    open-pull-requests-limit: 0
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: gomod
    open-pull-requests-limit: 0
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: pub
    open-pull-requests-limit: 0
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: gradle
    open-pull-requests-limit: 0
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: swift
    open-pull-requests-limit: 0
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    open-pull-requests-limit: 0
    directory: /
    schedule: { interval: weekly }
